---
corpusops_rancher_vbox_localaddr: "{% for i in ansible_all_ipv4_addresses %}{% if i.startswith('192') %}{{i}}{%endif%}{%endfor%}"
corpusops_rancher_vbox_stuff : 1
corpusops_rancher_vbox_url: "http://{{corpusops_rancher_vbox_localaddr}}:8080"
corpusops_rancher_vbox_telemetry: "true"
corpusops_rancher_vbox_admin: "rancheradmin"
corpusops_rancher_vbox_cfg: "/etc/rancher"
corpusops_rancher_vbox_password: "{{
    lookup('password',
           (corpusops_rancher_vbox_cfg+'/pwd_rancher_admin '
            'length=15 chars=ascii_letters,digits')) }}"
corpusops_rancher_vbox_api_v: "{{
    lookup('password',
           (corpusops_rancher_vbox_cfg+'/apiv_rancher_admin '
            'length=15 chars=ascii_letters,digits')) }}"
corpusops_rancher_vbox_api_k: "{{
    lookup('password',
           (corpusops_rancher_vbox_cfg+'/apik_rancher_admin '
            'length=15 chars=ascii_letters,digits')) }}"
corpusops_rancher_vbox_bins_dir: "/srv/apps/rancher"
